#!/usr/bin/env node
import { exec } from 'node:child_process';
import { promisify } from 'node:util';

const execAsync = promisify(exec);

async function main() {
  try {
    await execAsync('npx lint-staged');
  } catch (error) {
    process.exit(1);
  }
}

main();